# Generated by Django 3.2.8 on 2021-11-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewUkc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, db_column='USER_ID', max_length=100, null=True)),
                ('camping_name', models.CharField(blank=True, db_column='CAMPING_NAME', max_length=100, null=True)),
                ('rating', models.IntegerField(blank=True, db_column='RATING', null=True)),
                ('review', models.CharField(blank=True, db_column='REVIEW', max_length=255, null=True)),
            ],
            options={
                'db_table': 'REVIEW_UKC',
                'managed': False,
            },
        ),
    ]
